defmodule MyApp.Repo.Migrations.RequireNamesOnRepresentatives do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
    end

    alter table(:representatives) do
      modify :last_name, :text, null: false
      modify :first_name, :text, null: false
    end

    create table(:representative_tags, primary_key: false) do
      add :tag_id,
          references(:tags,
            column: :id,
            name: "representative_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :representative_id,
          references(:representatives,
            column: :id,
            name: "representative_tags_representative_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          primary_key: true,
          null: false
    end
  end

  def down do
    drop constraint(:representative_tags, "representative_tags_tag_id_fkey")

    drop constraint(:representative_tags, "representative_tags_representative_id_fkey")

    drop table(:representative_tags)

    alter table(:representatives) do
      modify :first_name, :text, null: true
      modify :last_name, :text, null: true
    end

    drop table(:tags)
  end
end
